import {
  ArrowRight,
  BadgeCheck,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Building2,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  CloudCog,
  Code2,
  Cpu,
  Database,
  DatabaseBackup,
  Eye,
  Gauge,
  HardDrive,
  Headset,
  Landmark,
  Leaf,
  LifeBuoy,
  Link as LinkIcon,
  Mail,
  MapPin,
  Menu,
  Moon,
  Package,
  Phone,
  Pill,
  Rocket,
  Ship,
  Search,
  Server,
  Send,
  Settings2,
  Shield,
  ShieldCheck,
  Sun,
  Twitter,
  Facebook,
  Linkedin,
  X,
  Zap,
} from "lucide-react";

const ICONS = {
  brightness_4: Moon,
  brightness_7: Sun,
  menu: Menu,
  close: X,
  bolt: Zap,
  rocket_launch: Rocket,
  expand_more: ChevronDown,
  dns: Server,
  sailing: Ship,
  database: Database,
  shield: Shield,
  code: Code2,
  headset_mic: Headset,
  cloud_sync: CloudCog,
  chevron_right: ChevronRight,
  verified_user: BadgeCheck,
  settings_suggest: Settings2,
  support_agent: LifeBuoy,
  location_city: Building2,
  apartment: Building,
  place: MapPin,
  location_on: MapPin,
  phone: Phone,
  email: Mail,
  support: Headset,
  mosque: Landmark,
  domain: Building,
  link: LinkIcon,
  business: BriefcaseBusiness,
  settings_input_component: Cpu,
  storage: HardDrive,
  business_center: Briefcase,
  check_circle: CircleCheck,
  verified: BadgeCheck,
  security: ShieldCheck,
  backup: DatabaseBackup,
  speed: Gauge,
  send: Send,
  mail_outline: Mail,
  arrow_forward: ArrowRight,
  search: Search,
  spa: Leaf,
  eco: Leaf,
  medication: Pill,
  inventory_2: Package,
  visibility: Eye,
  facebook: Facebook,
  linkedin: Linkedin,
  twitter: Twitter,
};

export default function Icon({ name, className = "", size = 20, strokeWidth = 2 }) {
  const Component = ICONS[name] || CircleCheck;
  return (
    <Component
      aria-hidden="true"
      className={className}
      size={size}
      strokeWidth={strokeWidth}
    />
  );
}
